name: Build with Cosmopolitan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Download cosmocc
        run: |
          curl -LO https://cosmo.zip/pub/cosmocc/cosmocc.zip
          unzip cosmocc.zip -d cosmocc
          echo "$PWD/cosmocc/bin" >> $GITHUB_PATH

      - name: Dump Minecraft server registries
        run: |
          mkdir notchian
          cd notchian
          curl -Lo server.jar https://piston-data.mojang.com/v1/objects/6bce4ef400e4efaa63a13d5e6f6b500be969ef81/server.jar
          echo "eula=true" > eula.txt
          java -DbundlerMainClass="net.minecraft.data.Main" -jar server.jar

      - name: Generate registry headers
        run: |
          bun run build_registries.js

      - name: Build project
        run: |
          cosmocc src/*.c -O3 -Iinclude -o bareiron.exe

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest build
          files: bareiron.exe
          overwrite: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
